README.md
features/received_command.feature

Change commanded to received_command in README.md
Fix "Multi Line Run Block" examples
Add Ruby syntax highlighting to code blocks
Fix internal links to headings

[readme] Fix some typos in README.md

---

README.md

docs: fixed examples for received_command

---

README.md

Fix issue https://github.com/boc-tothefuture/openhab-jruby/issues/26

docs: fix event.item to event.item.id in log messages

---

README.md
features/time_of_day.feature
lib/openhab/core/dsl/time_of_day.rb

Allows the following code
```ruby
if TimeOfDay.now < '15:00'
#do something
end
```
Update README.md

feat: allow TimeOfDay comparison against string

---

Rakefile

I noticed the test environment was still on 3.0.0.RC2, so I updated it to the release version.

build: update to openhab 3.0.0 in Rakefile

---

README.md
features/time_of_day.feature
lib/openhab/core/dsl/time_of_day.rb

This will make TimeOfDay.parse accept '7pm', '7 pm', '7:00pm', and '7 PM' as 19:00. The check is delegated to Java's DateTimeFormatter, so '13pm' will raise an error.

feat: TimeOfDay.parse understands am/pm

---

lib/openhab/core/dsl/time_of_day.rb

DateTimeFormatter uses the system Locale. US Locale needs upper case AM/PM whilst some other locale need lowercase am/pm. This PR creates a DateTimeFormatter that is case insensitive.

fix: TimeOfDay.parse am/pm case insensitive

---

docs/usage/misc/timers.md

I've recently submitted a PR to openhab-core to add Timer::getExecutionTime(). It's currently available in openhab 3.1 (snapshot).

docs: timer.execution_time

---

lib/openhab/core/duration.rb

This would make logging the duration a bit nicer.
I was creating a way to define all my motion triggers and what they would do, including a configurable trigger duration for each case. I'd like to log the duration for it and haven't found an easy way to show the duration.
Case in point:
```ruby
logger.info("Scheduling a timer for #{action_item.name} in #{config[:duration]}")
```
where config[:duration] is the Duration object e.g. `2.minutes`

feat: add Duration.to_s

---

docs/usage/misc/timers.md

Specified that execution_time is only available in openhab 3.1+

docs: timer execution_time

---

docs/usage/items.md
features/items.feature
lib/openhab/core/dsl/items/items.rb

Resolve #101 
Add items.include? to check for items existence
Make items['nonexistent'] to return nil. This will enable such shortcut:
```ruby
basename = 'LivingRoom'
power_item = items["#{basename}_Light_Dimmer"] ||  items["#{basename}_Light_Power"] ||  items["#{basename}_Light_Switch"]
power_item&.on
```

fix: items['nonexistent'] now returns nil, add items.include?

---

docs/usage/items/dimmer.md
features/dimmer_item.feature
lib/openhab/core/dsl/monkey_patch/items/dimmer_item.rb

Make DimmerItem comparable against a number, or another DimmerType, or a NumberType.
Implement to_s for DimmerItem to return the state / value.
I don't understand why I need to override the == operator in addition to <=> operator. The equality comparison does not call the spaceship <=> method for some reason.

feat: DimmerItem becomes comparable

---

Gemfile.lock
lib/openhab/core/dsl/rule/item.rb

It seems that this step is not necessary because `OpenHAB::Core::DSL::Groups` has a def_delegator for name, so GroupItem1.name resolves to GroupItem1.group.name and that's all that's needed by the triggers.
All the tests still passed without this.

refactor(group): remove special check for groups in triggers

---

.rubocop.yml
Gemfile.lock
docs/usage/misc/persistence.md
features/persistence.feature
lib/openhab/core/dsl.rb
lib/openhab/core/dsl/monkey_patch/items/items.rb
lib/openhab/core/dsl/monkey_patch/items/persistence.rb
lib/openhab/core/dsl/persistence.rb

Resolve #50 
Add Persistence methods to Items. It accepts a relative duration in addition to ZonedDateTime, e.g. 
```
Item1.average_since 12.hours #or
Item1.average_since ZonedDateTime.now.minusHours(12)
```
To specify the persistence service: (I dropped the idea of named parameter)
```
Item1.last_update 'influxdb'
Item1.sum_since 1.hour, :influxdb #it could accept a symbol
```

feat: Support Persistence features

---

lib/openhab/core/dsl/time_of_day.rb

perf(timeofdayrangeelement): subclass Numeric to make comparisons more efficient

---

docs/usage/ui-rules.md

Just a quick write-up on how to create rules in the UI, to avoid confusion from users taking that path. Note that one of the examples requires that #134 is merged, so might want to hold off this until then. Feel free to add more examples!

docs: document UI created rules

---

docs/usage/ui-rules.md

There was some formatting issues due to missing blank lines between list and code section.

docs(ui-rules): add blank lines to fix formatting

---

Gemfile.lock
docs/usage/items/number.md
features/comparisons.feature
lib/openhab/dsl/units.rb

I noticed that the common units from OpenHAB core isn't imported. This PR will allow the use of various units available without having to import them in the user scripts
* WATT
* AMPERE
* VOLT
* ONE
* PERCENT
* NEWTON
* HERTZ
* SECOND
* MINUTE
* HOUR
* DAY
* WEEK
* YEAR
* LITRE
* etc
With this, user scripts can now refer to, e.g.  `Units::VOLT` without having to add `java_import org.openhab.core.library.unit.Units` at the top of the scripts.

feat(units): import OpenHAB common units for UoM

---

docs/usage/items/datetime.md

I was just reading the announcement and clicked on the doc. Noticed a one letter typo.

docs: fix typo on datetime doc

---

features/changed_duration.feature
lib/openhab/dsl/rules/automation_rule.rb

Fixes #163 
Just had to restructure the logic in the `process_trigger_delay` so it always processes the trigger if a timer for that trigger is active.
Added test to verify.

fix(changed_duration): cancel 'changed for' timer correctly

---

Gemfile.lock
features/rule_language.feature
lib/openhab/dsl/rules/automation_rule.rb

I noticed that `otherwise` blocks are always executed regardless of guard conditions. This PR fixes that issue.

fix(rule): otherwise blocks are always executed

---

docs/usage/misc/metadata.md
features/metadata.feature
lib/openhab/dsl/monkey_patch/items/metadata.rb

Added a dig method to the top level metadata namespace, so you can include all levels in a single query and not worry about if one level is missing.
Fixes #158 

feat: add dig-method to top level metadata

---

Gemfile.lock
features/items.feature
lib/openhab/dsl/monkey_patch/items/items.rb

When the Item's state is NULL or UNDEF, `"#{Item}"` will expand to the object's address instead of saying NULL or UNDEF. This PR will fix this.
Fix #173

fix(items): to_s did not include UNDEF and NULL

---

Gemfile.lock
features/changed_duration.feature
lib/openhab/dsl/monkey_patch/ruby/string.rb
lib/openhab/dsl/rules/automation_rule.rb

The from: and to: comparison for changed_duration on StringItem didn't work, because Ruby String didn't know how to compare against Openhab StringType. This PR should fix it.

fix(changed_duration): stringitem from/to comparison didn't work

---

Gemfile.lock
docs/usage/misc/persistence.md
features/persistence.feature
lib/openhab/dsl/monkey_patch/items/persistence.rb

This PR makes return value of the persistence functions converted to Quantity with the same unit as the attached NumberItem
Somewhat related to #153 which will apply more generically to any DecimalType data, whereas this PR applies specifically to persistence without having to specify the unit.

feat(persistence): automatically convert to quantity for dimensioned items

---

docs/usage/misc/metadata.md
features/metadata.feature
lib/openhab/dsl/monkey_patch/items/metadata.rb

Instead of 
```ruby
Item1.meta['ns'] = event.last.to_s # This could be a StringType, or any other type / object
```
This PR calls the object's to_s so we can do:
```ruby
Item1.meta['ns'] = event.last
```

fix(metadata): convert value to string before assignment

---

docs/usage/misc/persistence.md

Inter-document linking is a bit tricky. I needed to go one more level up on the link.

docs(persistence): fix wrong link to quantity

---

features/run.feature
lib/openhab/dsl/monkey_patch/events/events.rb
lib/openhab/dsl/monkey_patch/events/item_event.rb
lib/openhab/dsl/monkey_patch/events/item_state_changed.rb
lib/openhab/dsl/rules/automation_rule.rb

Resolve #189 
Instead of looking up and decorating items every time a run / triggered block is encountered, which can occur multiple times when there are multiple run/trigger blocks, the lookup and decoration is done only once in the monkey patched event.

refactor(event.item): monkey patch ItemEvent to provide decorated event.item

---

lib/openhab/dsl/items/datetime_item.rb
lib/openhab/dsl/items/item_command.rb
lib/openhab/dsl/items/number_item.rb
lib/openhab/dsl/items/rollershutter_item.rb
lib/openhab/dsl/items/string_item.rb
lib/openhab/dsl/monkey_patch/items/contact_item.rb
lib/openhab/dsl/monkey_patch/items/dimmer_item.rb
lib/openhab/dsl/monkey_patch/items/switch_item.rb

Added the ability to automatically detect accepted states/command from the OH item. Or is that too much?
Had to create a dummy item, because the `getAccepted*Types`-methods are instance methods. Or is there a way to read private static fields from jruby?

refactor: automatically infer accepted types from OH item

---

lib/openhab/dsl/types/datetime.rb

Have defined the methods to be compatible with ruby's Time class, but removed the need to create a new Time instance for most methods.

perf(datetime): delegate more methods directly to ZonedDateTime

---

features/rule_language.feature
lib/openhab/dsl/rules/automation_rule.rb
lib/openhab/dsl/rules/rule.rb
lib/openhab/log/logger.rb

Added some rescue clauses to catch errors in scripts and log them along with stack traces. If the error is in the parsing of the file the error is re-raised to the ScriptEngineManager, but with the stack trace added. If the error is raised when the rule is executed it is handled internally and logged together with the stack trace. The errors are rescued for a single execution block, which allows other blocks in the same rule to run as usual.
In both cases the stack frames pertaining to internal classes/methods (script-library and jruby) are removed, so only the lines relevant to the end user are shown.
WDYT?
Fixes #17

feat: add stack trace to errors

---

lib/openhab/dsl/monkey_patch/items/metadata.rb
lib/openhab/dsl/rules/guard.rb
lib/openhab/dsl/types/quantity.rb

I went through the library and only found these three instances where logging could be further optimised
Resolve #194

perf(logging): use block syntax to log method calls

---

.rubocop.yml
features/step_definitions/openhab_rules.rb
features/support/openhab.rb
features/support/openhab_rest.rb
lib/openhab/dsl/items/player_item.rb
lib/openhab/dsl/rules/guard.rb
lib/openhab/dsl/rules/rule_config.rb
rakelib/docs.rake
rakelib/openhab.rake

This came up when creating the player item. 
```
item_type Java::OrgOpenhabCoreLibraryItems::PlayerItem, play?: :playing?, pause?: :paused?,
rewind?: :rewinding?, fastforward?: :fastforwarding?
```
The colon syntax for hashes, is in my opinion, a lot less readable when both the values are symbols.
I believe that this is much more readable:
```
item_type Java::OrgOpenhabCoreLibraryItems::PlayerItem, :play? => :playing?, :pause? => :paused?,
:rewind? => :rewinding?, :fastforward? => :fastforwarding?
```
There is an option in rubocop to use and enforce this style which this PR does.
See this issue for more discussion: https://github.com/rubocop/rubocop/issues/1437
Any issues @jimtng or @pacive ?

refactor(hash): use hashrockets for hashes that have keys as values

---

features/comparisons.feature
features/datetime_item.feature
features/rollershutter_item.feature
features/units_of_measurement.feature
lib/openhab/dsl/items/datetime_item.rb
lib/openhab/dsl/monkey_patch/items/contact_item.rb
lib/openhab/dsl/monkey_patch/items/switch_item.rb
lib/openhab/dsl/monkey_patch/ruby/string.rb
lib/openhab/dsl/monkey_patch/types/on_off_type.rb
lib/openhab/dsl/monkey_patch/types/open_closed_type.rb
lib/openhab/dsl/monkey_patch/types/up_down_type.rb
lib/openhab/dsl/types/datetime.rb

Made some additions to make more comparisons work bi-directionally. Also moved some comparison tests into `comparisons.feature` to speed up the test runs a little.
Most notably made Switch and Contact Items comparable to each other.
**Question:** Do we want to support everything bi-directionally, or should we discourage Yoda-syntax such as
```ruby
CLOSED == ContactItem
```
Fixes #205 

feat: support more comparisons

---

features/rule_language.feature
features/step_definitions/openhab.rb
features/support/env.rb
features/support/openhab.rb
lib/openhab/log/logger.rb

Doesn't get as clean as ruby exceptions, but cleans out the jruby stack frames and just leaves the java ones.
Fixes #220 

fix: handle native java exceptions in clean_backtrace

---

docs/usage/misc/persistence.md
features/persistence.feature
lib/openhab/dsl/monkey_patch/items/persistence.rb

This resolves #208 
```ruby
midnight = ZonedDateTime.now.withHour(0).withMinute(0).withSecond(0)
max = Solar_AC_Power.maximum_since(midnight, :influxdb)
logger.error("Max since: #{max}, occurred at: #{max.timestamp}") # here we can use #{max} instead of #{max.state}
```

feat(persistence): convert HistoricItem methods to directly return its state

---

docs/usage/things.md
features/thing.feature
lib/openhab/dsl/things.rb

Boolean methods are available based on ThingStatus. 
| Method          | Description                                   |
| --------------- | --------------------------------------------- |
| `unitialized?`  | Returns true if the status is `UNINITIALIZED` |
| `initializing?` | Returns true if the status is `INITIALIZING`  |
| `unknown?`      | Returns true if the status is `UNKNOWN`       |
| `online?`       | Returns true if the status is `ONLINE`        |
| `offline?`      | Returns true if the status is `OFFLINE`       |
| `removing?`     | Returns true if the status is `REMOVING`      |
| `removed?`      | Returns true if the status is `REMOVED`       |
Example:
```ruby
things['uid'].online?
```

feat(thing): add boolean methods for checking thing's status

---

features/items.feature
lib/openhab/dsl/items/item_delegate.rb
lib/openhab/dsl/states.rb

This PR contains two separate commits, which when combined, will resolve #241
The first commit adds oh_item method to decorated items through def_item_delegator, so that all decorated item classes will have oh_item method that returns the underlying openhab object.
This in turn is utilised by the second commit to fix the problem with store_states.

Add oh_item to decorated items and fix store_states

---

features/gem_install.feature
features/quantity.feature
features/rule_language.feature
features/units_of_measurement.feature
lib/openhab/dsl/items/number_item.rb
lib/openhab/dsl/monkey_patch/items/items.rb
lib/openhab/dsl/monkey_patch/types/decimal_type.rb
lib/openhab/dsl/types/quantity.rb
lib/openhab/dsl/units.rb
rakelib/github.rake
rakelib/openhab.rake

Ensure compatibility with the new UoM library introduced in OH 3.1 while maintaining backwards-compatibility with previous OH-versions.
Replaces direct references to the UoM library with OH proxies, which should improve stability.
Other changes in OH causes somewhat different output when calling toString() on Number Items, added explicit formatting in several tests to compensate for this.
Some tests used calculations with temperatures in ways that doesn't work in the real world due to the nature of temperature scales, these were removed.
Finally configures the rest api to allow basic auth in the testing setup, since this is disabled by default in OH 3.1
Closes #245 

refactor: make compatible with new UoM library

---

lib/openhab/dsl/monkey_patch/items/items.rb

OH 3.1.0.M5 changed the string parser for Number Items, so it no longer accepts the format output by BigDecimal.to_s. This fix calls `to_java.to_plain_string` on all BigDecimal values before they're sent to the event bus, so they can be parsed correctly.

fix(items): format BigDecimal state as a string the parser accepts

---

features/items.feature
lib/openhab/dsl/items/item_delegate.rb

Resolve #252 by delegating decorated items' #hash to GenericItem.hashCode() as suggested by @pacive in https://github.com/boc-tothefuture/openhab-jruby/pull/253#issuecomment-853558929

fix(items): decorated items could not be used as hash keys

---

docs/usage/misc/duration.md
features/timer.feature
lib/openhab/dsl/monkey_patch/ruby/number.rb

closes #263
have to actually do math to not lose precision finer than 1ms,
and then truncate to integer once we're at ms

feat(duration): support duration methods on Float too

---

.github/workflows/workflow.yml
docs/installation/index.md
docs/usage/misc/shared_code.md
features/gem_install.feature
features/shared_code.feature
features/step_definitions/openhab.rb
features/step_definitions/openhab_rules.rb
features/support/openhab.rb
lib/openhab.rb
lib/openhab/core/load_path.rb
rakelib/openhab.rake

since it doesn't seem to be happening by JRuby embedded automatically,
do it manually. also document that this is the preferred way to share
code among multiple rules

feat(load_path): apply $RUBYLIB

---

.gitignore

bundler supports gems.rb as an alternate name for Gemfile. I haven't
tracked down exactly when bundler tries to run for gems.rb as the
Gemfile, but it keeps poppig up in my local repo

fix(dev): ignore lockfile for file named gems.rb

---

features/received_command.feature
lib/openhab/dsl/items/group_item.rb

while #members is the documented method, this reduces confusion because
the "global" Items#items is being leaked onto this object. so this hides
the global, and makes it behave as you expect

feat(group_item): alias items to members

---

lib/openhab/dsl/items/group_item.rb
lib/openhab/dsl/items/items.rb
lib/openhab/dsl/rules/triggers/command.rb
lib/openhab/dsl/rules/triggers/trigger.rb
lib/openhab/dsl/rules/triggers/updated.rb
lib/openhab/dsl/things.rb

a common use case is to use `items[dynamic_item_name]` or
`things[dynamic_thing_name]` to get a non-constant item or thing.
the old code would instantiate a new array or set of all items/things
in OpenHAB, and then immediately discard it when the [] method is used
to look up the item individually. this change delays instantiating
until an actual enumerable method is used

fix(things, items): avoid wrapping every OpenHAB object

---

features/decimal_type.feature
lib/openhab/dsl/monkey_patch/types/decimal_type.rb

so that you can inspect them directly from an event.state or event.was, without an Item involved.

feat(DecimalType): zero?, positive?, negative? predicates directly on DecimalType

---

features/rule_language.feature
lib/openhab/dsl/rules/triggers/changed.rb
lib/openhab/dsl/rules/triggers/command.rb
lib/openhab/dsl/rules/triggers/updated.rb

The source code documentation stated that trigger methods (update, changed, received_command) return the OpenHAB triggers. However they just return the items being passed to them. 
This PR makes a slight modification so that these methods return the openhab trigger objects.

fix(triggers): trigger methods return the trigger objects

---

lib/openhab/core/osgi.rb
lib/openhab/dsl/rules/triggers/cron.rb
lib/openhab/dsl/things.rb

I could only find three extra java_imports, so it's a very tiny PR.

refactor(imports): remove extraneous java_import

---

docs/usage/execution/run.md
docs/usage/triggers.md
features/attachments.feature
features/step_definitions/support.rb
lib/openhab/dsl/rules/automation_rule.rb
lib/openhab/dsl/rules/item_event.rb
lib/openhab/dsl/rules/rule.rb
lib/openhab/dsl/rules/rule_config.rb
lib/openhab/dsl/rules/triggers/changed.rb
lib/openhab/dsl/rules/triggers/channel.rb
lib/openhab/dsl/rules/triggers/command.rb
lib/openhab/dsl/rules/triggers/trigger.rb
lib/openhab/dsl/rules/triggers/updated.rb

This is a WIP with RFC.
As I am converting more and more rules to jruby I am hitting the same pattern, in which I have multiple rules that are 99% similar but I want to do something slightly different based on the triggers, so I end up with duplicate rules.
For example:
```
def check_garage_doors(reason)
open_doors = groups['GarageDoors'].select(&:open?)
logging.debug("#{open_doors.length} garage doors open")
open_doors.map{ |door| "#{reason} and #{door.label} is open" }
.each { logger.warn(text); notify(text) }
end
rule 'Check garage doors at night' do
every :day, at: '8pm'
run { check_garage_doors "It's 8PM"}
end
rule 'Check garage doors when alarm armed for night' do
changed Alarm_Mode, to: [10,14]
run { check_garage_doors "Night mode set"}
end
```
The problems with this are:
1. The …

feat(attachments): adds attachments to triggers

---

features/comparisons.feature
features/dimmer_item.feature
lib/openhab/dsl/items/color_item.rb
lib/openhab/dsl/items/date_time_item.rb
lib/openhab/dsl/items/location_item.rb
lib/openhab/dsl/items/numeric_item.rb
lib/openhab/dsl/types/date_time_type.rb
lib/openhab/dsl/types/decimal_type.rb
lib/openhab/dsl/types/hsb_type.rb
lib/openhab/dsl/types/point_type.rb
lib/openhab/dsl/types/quantity_type.rb
lib/openhab/dsl/types/string_type.rb
lib/openhab/dsl/types/type.rb

fixes #328
ruby actually allows coerce to return nil (see
https://github.com/jruby/jruby/blob/9.2.19.0/core/src/main/java/org/jruby/RubyRange.java#L755,
https://github.com/jruby/jruby/blob/a309a88614916621de4cc5dc3693f279dae58d0c/core/src/main/java/org/jruby/RubyNumeric.java#L640,
https://github.com/ruby/ruby/blob/4fb71575e270092770951e6a69bf006c71fadb55/numeric.c#L477)
in light of that, don't raise TypeError ourselves in coerce methods, but
update our uses of coerce to check the return value, and handle
appropriately:
* return nil from <=> if coercion failed
* return false from == if coercion failed
* raise a type error in arithmetic operations if coercion failed

fix(type): allow comparison against incompatible types

---

features/timer.feature
lib/openhab/dsl/timers.rb

Resolves #342
Whenever a timer is "re-entered", the existing timer simply gets cancelled (and therefore removed from timer manager) and then a new one is created. This is done so the resulting timer gets the new duration and it will therefore use it for subsequent `#reschedule`.
Note that openhab's own implementation for reschedule is the same - it would cancel the current timer and create a new timer. https://github.com/openhab/openhab-core/blob/79edf2b9e643ad802c31b2e5f54edb93534277fd/bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java#L55-L61

fix(reentrant_timer): reset the timer duration to the latest call

---

.github/workflows/workflow.yml
.rubocop.yml
docs/contributing/index.md
docs/usage/items.md
docs/usage/items/datetime.md
docs/usage/items/groups.md
docs/usage/items/number.md
docs/usage/items/string.md
docs/usage/misc/duration.md
docs/usage/misc/metadata.md
docs/usage/things.md
openhab-scripting.gemspec

* change rubocop target
* update gemspec requirements (this means if you don't
upgrade the jruby bundle in openhab it will refuse to install any
future versions of the gem, which will have been tested against
ruby 2.6/jruby 9.3)
* update github workflow to use ruby 2.6
* update any documentation links to use 2.6.8 instead of 2.5.x

fix(dev): target ruby 2.6

---

lib/openhab.rb
rakelib/openhab.rake

Two things fixed #396 and #366 
- Use `singlethread` instead of `threadsafe` - this is the main cause of the problem
- Use include instead of extend for `OpenHAB::Core::ScriptHandling` 
Someone more knowledgeable can probably explain this better. According to https://github.com/jruby/jruby/wiki/RedBridge#Context_Instance_Type In `threadsafe`, there's only a single ScriptingContainer, shared across all the engine instances(?) I am not sure whether this means that the namespace for methods are shared?
In `singlethead` (and  also `singleton`) mode, each engine gets its own ScriptingContainer. 
This will require changing the default local_context to 'singlethread' within the automation add-on, as well as updating its docs.

fix(script_handling): scriptLoaded and scriptUnloaded not executed

---

README.md

I just noticed the readme on github page still says alpha.

docs(readme): change to beta

---

lib/openhab/dsl/timers/timer.rb

jruby translates `isSomething()` to `something?` by default

fix(timer): remove redundant delegators

---

rakelib/github.rake

Remove OpenHAB 3.0 from testing as discussed in #403

ci(build): drop support for OpenHAB 3.0

---

features/quantity_type.feature
lib/openhab/dsl/types/quantity_type.rb

The `#|` method is redundant. String argument is already implemented in openhab-core 
https://github.com/openhab/openhab-core/blob/598245b9197a26d1e4a64748cbd211a8fe8ff0c8/bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java#L277-L284

refactor(quantity_type): remove | method and alias it to to_unit

---

docs/usage/misc/timers.md

Document the new `cancelled?` just merged in https://github.com/openhab/openhab-core/pull/2570

docs(timers): add cancelled? to the documentation

---

features/changed_duration.feature
lib/openhab/dsl/rules/triggers/changed.rb

This allows to create delayed changed triggers for multiple states, eg:
```rb
changed Alarm_Mode, from: [8, 10], to: [11, 14], for: 10.seconds 
changed Alarm_Mode, from: 8, to: 11, for: 10.seconds 
changed Alarm_Mode, from: 8, to: 14, for: 10.seconds 
changed Alarm_Mode, from: 10, to: 11, for: 10.seconds 
changed Alarm_Mode, from: 10, to: 14, for: 10.seconds 
```
Before it was possible to do so without a delay but broke by adding a `for: ...`, that's why I think this is a bugfix.

fix(trigger): create multiple delayed triggers for array from/to states

---

features/between.feature

We are hitting this error because this test tries to create MonthDate(11, 31) and 31 is not a valid date for november. As a result, tests will fail.

test(between): fix monthday's out of range error

---

features/between.feature
features/comparisons.feature
features/dimmer_item.feature
features/groups.feature
features/received_command.feature
features/rollershutter_item.feature
lib/openhab/dsl/types/type.rb

Resolve #365 
**This could potentially be a breaking change.**
`case` comparisons must now use the underlying type.
Case in point:
```ruby
RollerShutterItem1 << DOWN
case RollerShutterItem1
when DOWN then logger.info("It will no longer reach here")
when 100 then logger.info("It will reach here: 100")
end
```
I believe this is the correct / non ambiguous behaviour. It also allows precision handling of commands sent to items that support multiple types, which is the whole reason for this PR.
Example:
```ruby
rule 'x' do
received_command RollerShutterItem1
run do |event|
case event.command
when 0..100 then logger.info("A specific position has been commanded")
when DOWN then logger.info("DOWN command received")
end
end
end
RollerShutterItem1 << DOWN
```
The following will still evaluate to …

fix(comparisons): === should perform an exact type match for case statements

---

docs/usage/things.md
docs/usage/triggers/channel.md
features/channels.feature
features/thing.feature
lib/openhab/dsl/dsl.rb
lib/openhab/dsl/rules/triggers/channel.rb
lib/openhab/dsl/things.rb
lib/openhab/dsl/uid.rb

this is useful if you're auto-discovering the channels by filtering the known things

feat(channel_trigger): allow setting channel triggers directly from channel/thing objects

---

docs/usage/misc/timers.md
docs/usage/triggers/changed.md
features/changed_duration.feature
features/timer.feature
lib/openhab/dsl/timers/timer.rb

item's state is evaluated as number of seconds for timer. Eg with a
`Alarm_Delay` `NumberItem` this is now possible:
```rb
after Alarm_Delay { ... }
changed Alarm_Mode, for: Alarm_Delay
```
when rescheduling, the item's state will be revaluated.

feat(timers): support passing `NumberItem` as timer duration

---

docs/usage/misc/month_day.md
features/comparisons.feature
lib/openhab/dsl/time/month_day.rb

Fix #377 - MonthDay.of(10, 10) == '10-10' wasn't working before.
Allows MonthDay.parse('2-3') format, which is the same as MonthDay.parse('02-03') for the lazy people like me. Also allows leading `--` if provided.
Added docs.

fix(monthday): fix equality comparison against string and allow parsing single digit month-days

---

features/items.feature
lib/openhab/dsl/items/generic_item.rb

OpenHAB allows you to reference a group item that doesn't exist
(so that it doesn't matter which file your define the group item
in), but we shouldn't be returning nils from `groups`.

fix(item_groups): fix Item#groups returning nil sometimes

---

docs/usage/misc/timers.md
features/timer.feature
lib/openhab/dsl/timers/manager.rb

I got tired of writing `timers[id].each(&:cancel)`. This PR makes it possible to call `timers[id].cancel_all`

feat(timer): add timers[id].cancel_all shorthand for timer[id].each(&:cancel)

---

rakelib/openhab.rake

I often came across an error where it "failed" to stop openhab, simply because it needed to wait a bit longer. This extends the wait time.

ci(stop): wait longer for openhab to stop

---

docs/usage/misc/logging.md
features/gem_install.feature
features/logging.feature
features/step_definitions/openhab.rb
features/support/env.rb
lib/openhab/log/configuration.rb
rakelib/openhab.rake

Resolve #464 
jsr223.jruby is a custom log prefix that would require users to specifically enable in the karaf console. This is an extra step that could be avoided to improve user's first time experience.
org.openhab prefix is set to INFO by default
In Openhab 3.2 distro, a new prefix was created `org.openhab.automation.script`, however it is set to TRACE by default, making it impractical for us to use.
This PR chose `org.openhab.automation.jruby` as a unique log prefix to use, relying on the `org.openhab` default as INFO.

refactor(logging)!: rename log prefix from jsr223.jruby to org.openhab.automation.jruby

---

features/step_definitions/openhab.rb
features/support/openhab.rb

Resolve #481 
Skip feature installation (which includes a 60 second wait) if it's already installed, instead of re-installing it (and waiting for 60 seconds) for each scenario.

ci(feature_installation): do not reinstall openhab feature

---

features/gem_install.feature
lib/openhab/dsl/types/date_time_type.rb
lib/openhab/dsl/types/decimal_type.rb
lib/openhab/dsl/types/hsb_type.rb
lib/openhab/dsl/types/increase_decrease_type.rb
lib/openhab/dsl/types/next_previous_type.rb
lib/openhab/dsl/types/on_off_type.rb
lib/openhab/dsl/types/open_closed_type.rb
lib/openhab/dsl/types/percent_type.rb
lib/openhab/dsl/types/play_pause_type.rb
lib/openhab/dsl/types/point_type.rb
lib/openhab/dsl/types/quantity_type.rb
lib/openhab/dsl/types/refresh_type.rb
lib/openhab/dsl/types/rewind_fastforward_type.rb
lib/openhab/dsl/types/stop_move_type.rb
lib/openhab/dsl/types/string_type.rb
lib/openhab/dsl/types/un_def_type.rb
lib/openhab/dsl/types/up_down_type.rb

Resolve #482 
This PR makes openhab-jruby library compatible with the fix to be made in the jrubyscripting bundle that addresses #482. This PR should be compatible with the bundle before the fix (i.e. the bundle that shipped with openhab 3.2) as well.

fix(java_class): fix java to ruby class

---

features/groups.feature
lib/openhab/dsl/items/item_registry.rb

OpenHAB's DSL rules doesn't, and it can be surprising and annoying when you're
trying to find an item by using Enumerable methods (i.e. `select`)
against items and your item doesn't show up just because it happens
to be a GroupItem. especially since hash lookup (`items["GroupItem"]`)
doesn't have the same restriction.

fix(items): don't exclude GroupItems from `items` global hash

---

lib/openhab/dsl/types/date_time_type.rb
lib/openhab/dsl/types/hsb_type.rb
lib/openhab/dsl/types/percent_type.rb
lib/openhab/dsl/types/point_type.rb
lib/openhab/dsl/types/quantity_type.rb

Resolve #312 for the current addon and compatible with the upcoming fix in the addon
Furthermore, this also renames the alias `ONE` in quantity_type.rb to `ONE_UNIT` so as not to override the actual QuantityType::ONE from OpenHAB-core

fix(types): fix already initialized warning

---

lib/openhab/log/logger.rb

fix(logger): incorrect logger prefix on non standard gem_home path

---

features/changed_duration.feature
features/support/openhab.rb

Resolve #507 and #493
This is split into 3 commits:
* changed_duration saves about 5 minutes off the test time for changed_duration.feature
* delete_rules: delete *.rb files after REST calls to avoid race conditions encountered in #493
* delete_items: delete *.items files after REST calls
I'm combining the fixes and the changed_duration to avoid test failures when testing the changed_duration rules.
Overall, this reduced the total test time from 17-25mins down to about 13.5mins

test fixes (delete_rules and delete_items) and speed up changed_duration

---

features/string_type.feature
lib/openhab/dsl/types/string_type.rb

* StringType#inspect should call String#inspect, not StringType#toFullString
or whatever java-ism JRuby defaults to.
* StringType#=~ should work properly, instead of just defaulting to calling
StringType#==

fix(string_type): direct regex comparison and inspect

---

rakelib/openhab.rake

Resolve #412
We can run `rake openhab:cleanupgems` to uninstall all openhab-scripting gems and start fresh.
Open to suggestions for a better name or a different way to do this.

ci(gems): add a task to uninstall openhab-scripting gems

---

features/logging.feature
lib/openhab/log/logger.rb

Fix #523
Because OpenHAB::Log gets included into the top level, the OpenHAB::Log::Logger class then lives on the top level. Due to its generic name, it can be reopened/modified by other libraries that innocently creates their own Logger class. In some cases this can cause errors.
Some libraries known to cause such a problem are httparty and koala.
This PR moves OpenHAB::Log::Logger class to OpenHAB::Core::Logger avoid this issue.

fix(logger): move logger class into core module to prevent unintentional modification

---

lib/openhab/dsl/monkey_patch/actions/script_thing_actions.rb

[Recent changes in openhab-core](https://github.com/openhab/openhab-core/pull/2723) (a snapshot **After** 3.3.0M1) broke script_thing_actions.rb
```
22:49:28.099 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/ruby/test2.rb': Error during evaluation of Ruby in /openhab/conf/scripts/ruby/lib/gem_home/gems/openhab-scripting-4.32.0/lib/openhab/dsl/monkey_patch/actions/script_thing_actions.rb at line 22: (TypeError) ScriptThingActions is not a class
```
`org.openhab.core.automation.module.script.internal.defaultscope.ScriptThingActions` was renamed to `org.openhab.core.automation.module.script.internal.defaultscope.ScriptThingActionsImpl`
This PR should hopefully make it compatible with pre and post change.

fix(script_thing_actions): adapt to changes in openhab 3.3

---

lib/openhab/dsl/types/on_off_type.rb

I noticed when calling SwitchItem.toggle, one comparison was done when the item was in the ON state, but two comparisons were done when the item was in the OFF state.
* When SwitchItem1 is ON and SwitchItem1.toggle is called:
```
23:15:06.403 [TRACE] [.openhab.core.library.types.OnOffType] - (Java::OrgOpenhabCoreLibraryTypes::OnOffType) ON == ON (Java::OrgOpenhabCoreLibraryTypes::OnOffType)
23:15:06.406 [TRACE] [openhab.core.library.items.SwitchItem] - Sending Command OFF to Switch1
```
* When SwitchItem1 is OFF and SwitchItem1.toggle is called:
```
23:15:08.773 [TRACE] [.openhab.core.library.types.OnOffType] - (Java::OrgOpenhabCoreLibraryTypes::OnOffType) OFF == ON (Java::OrgOpenhabCoreLibraryTypes::OnOffType)
23:15:08.776 [TRACE] [.openhab.core.library.types.OnOffType] - …
```

refactor(on_off_type): reduce to one method call for #!

---

docs/installation/index.md

Update the installation instructions to include the [auto-require feature added to openhab 3.3](https://github.com/openhab/openhab-addons/pull/12381)

docs(installation): add information about auto-require feature

---

lib/openhab/log/logger.rb

Fix #533 by excluding <script> in the prefix

fix(logger): exclude <script> in log prefix

---

features/rule_language.feature
lib/openhab/dsl/rules/rule.rb

Related to #419 and #438
Reverts this back to the proper behaviour, which returns the added rule object. This populates the rule.uid which can be used for rule lookup. 
Note: in the `#process_rule_config`, `rule.uid` is blank/nil?. The uid is only available in the `added_rule`.

fix(rule): rule method returns the created rule

---

lib/openhab/dsl/items/timed_command.rb

Fix #525 
The timed command:
* Send a command to the item (e.g. ON)
* Set up a timer to revert that command (set it back to OFF)
* Set a rule that will cancel that timer if the state of the item changed. The issue is that here, it expects that the item had already changed to the desired state (ON) before the rule was created.
On a busy/slow system, the item might not have had a chance to change to ON before the rule in step 3 was created. 
When this happened, the rule will trigger due to the change of state (to ON which was initially commanded), cancel the timer, so that the item will never return to OFF.
This PR adds a condition to the rule to prevent this issue.

fix(timed_command): timed command cancelled by its own command

---

rakelib/github.rake

Unfortunately this would double our test time.

ci(openhab): add 3.3.0M2 to the build matrix

---

docs/_config.yml

@boc-tothefuture I wasn't sure whether you've added the google analytics, or was it from the original template? I don't mind it being there if you meant to have it.
Also if you want to add a specific copyright footer, that's OK too. The current one is just a bit confusing / misleading.

docs(config): remove footer, google analytics, update edit link

---

docs/_config.yml

It seems that the footer link isn't quite right. I don't know how to generate the pages locally.

docs(config): fix the edit on github footer link

---

features/ensure_states.feature
lib/openhab/dsl/items/ensure.rb

I noticed that ensure.update is in the docs but wasn't implemented.
Also GroupMembers doesn't have #update. At this point I don't think it's worth adding, as I don't think anyone needs it.

fix(ensure): implement ensure.update

---

features/items.feature

Installing systeminfo feature caused openhab to restart on 3.3.0.M2 and it is the main reason for test failures.
This is part of the test improvement PR but because the uidoc merge seems to have issues, I'm pushing/merging this to regenerate the docs.

test(items): remove systeminfo feature from test

---

features/support/openhab.rb
rakelib/openhab.rake

See #548 
* Check for system start level for openhab's readiness. This should address the issue when Rest requests sometimes hit a 404 because openhab's rest bundle isn't loaded yet.
* Restore the optimized openhab client, except when doing feature:install. This seems to save about 5 minutes off the test time.
* when not using the optimized client, call cmd.run! which doesn't raise an exception on error. This allows wait_until to keep retrying even after encountering (temporary) errors.
Note: feature:install openhab-binding-systeminfo caused openhab to restart on 3.3.0.m2

test: improve test reliability on openhab 3.3

---

docs/usage/ui-rules.md

Found an incorrect link on the ui-rules page.

docs(ui-rules): fix the link to configuration

---

docs/usage/triggers/cron.md
docs/usage/triggers/every.md
features/cron.feature
features/every.feature
lib/openhab/dsl/rules/triggers/cron/cron.rb

* Support using MonthDay for every, e.g. `every MonthDay.of(12, 25)` and `every '12-25'`
* Support using field names for cron, e.g.`cron second: 0, minute: 10, hour: 15, dow: 'MON,TUE,FRI'`
* Correct some typos in the corresponding docs
Previously I'd have to use a guard with every because it cannot be restricted to a specific monthday, resulting in the trigger firing every day at a specific time. By accepting monthday, the cron trigger can fire just once on the desired monthday.
The field names on cron makes it easier to remember. I normally had to look up the cron docs every time even though I'm only interested in certain fields.

feat(cron): support fields for cron and monthday object for every

---

docs/usage/misc/state.md
docs/usage/misc/store_states.md
features/states.feature
lib/openhab/dsl/states.rb

`state?` returns true if all the given items have a valid state (not UNDEF or NULL).
| Parameter       | Description                                                                                                                                                                    |
| --------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| `items`         | One or more items to check                                                                                                                                                     |
| `things:` | Default: `false` - do not check for linked things status. When `things:` is set to `true`, only return true …

feat(states): add state? helper method

---

docs/usage/misc/duration.md
docs/usage/misc/persistence.md
docs/usage/misc/timers.md
features/persistence.feature
features/timer.feature
lib/openhab/dsl/items/persistence.rb
lib/openhab/dsl/timers/timer.rb

Add support for 
* `after(ZonedDateTime.now.plus_minutes(xx))` (or create_timer)
* `after(Time.now + xx)`
* `Item.persistence_method(Time.now - xxx)`
I needed to use Item.historic_state from a specific date. ZonedDateTime is a bit onerous to use e.g.
```
start_date = ZonedDateTime.of(2021, 12, 23, 0, 0, 0, 0, ZoneId.system_default)
start_value = Item.historic_state(start_date)
```
With this PR I could use `start_date = Time.new(2021, 12, 23)`.

feat: add support for timer and persistence to accept zoneddatetime and rubytime

---

docs/examples/how_do_i.md
docs/index.md
docs/ruby-basics.md
docs/usage/misc/logging.md
docs/usage/misc/time_of_day.md
docs/usage/triggers/cron.md

* Add more examples in a similar structure to jython docs from https://openhab-scripters.github.io/openhab-helper-libraries/Guides/But%20How%20Do%20I.html
* Some minor changes to the examples on the main page
* Additions to the logging page
* Add safe navigation to the Ruby Basics page
* Fix an error in the cron documentation

docs: add how do I examples

---

docs/usage/misc/logging.md

This fixes the incorrect logger documentation in #567

docs(logger): fix level check methods

---

docs/examples/how_do_i.md
features/actions.feature
features/date_time_item.feature
features/every.feature
features/persistence.feature
features/rule_language.feature
features/timer.feature
lib/openhab/dsl/dsl.rb
lib/openhab/dsl/imports.rb
lib/openhab/dsl/items/timed_command.rb
lib/openhab/dsl/rules/automation_rule.rb
lib/openhab/dsl/timers/timer.rb
lib/openhab/dsl/types/date_time_type.rb

Move the java_import for ZonedDateTime to the top of dsl.rb so it's available for user scripts.
Remove instances of `java_import java.time.ZonedDateTime` in other places
This makes it no longer necessary to import ZonedDateTime within user scripts even on openhab 3.2.
This also deduplicates the multiple imports in submodules.
By "importing", I mean re-assigning the ZonedDateTime constant to the Ruby class version. I'm not sure how "expensive" this operation is, but I suspect it's very "cheap" / fast to execute.

fix(zoneddatetime): make ZonedDateTime available on OpenHAB 3.2

---

docs/usage/triggers/watch.md
features/attachments.feature
features/rule_language.feature
features/watch.feature
lib/openhab/dsl/openhab.rb

Resolve #528 
`__conf__` is still available. It calls `OpenHAB.conf_root` with the YARD tag `@deprecated`. It may/should be removed in a future breaking change.

feat(conf): rename __conf__ to OpenHAB.conf_root

---

docs/examples/how_do_i.md
docs/index.md
docs/usage/misc/timers.md
features/timer.feature
lib/openhab/dsl/timers/manager.rb

Most of the time, only one reentrant timer is created / manipulated, so adding a helper method to cancel and reschedule would be nice.
* Add timers[id].reschedule as an alias for timers[id].each(&:reschedule)
* Add timers[id].cancel as an alias for timers[id].each(&:cancel) - the previous timers[id].cancel_all is made an alias for cancel.
* Minor tweak to the timers doc

feat(timers[]): add #reschedule, rename #cancel_all to #cancel

---

features/states.feature
features/time_of_day.feature
rakelib/openhab.rake

Fix #576
Working in my time zone, I sometimes trigger the tests near utc midnight. As a result, comparisons like
`TimeOfDay.now < (Time.now + 5*60).strftime('%H:%M:%S')` would return `false` when now >= `23:55:00`. This would cause the test to fail when running within this 5-minute window before midnight.
So I shifted the test to comparing TimeOfDay.noon against static time strings

test: add http readiness check

---

docs/contributing.md
features/support/openhab_rest.rb
rakelib/openhab.rake

Resolve #471
I got tired of the slow reloading of filewatcher on OSX, so I moved my development instance to my Linux server, and work remotely using vscode over SSH.
These changes are needed because that linux server also runs my production instance of openhab and the ports conflicted.

ci(ports): allow custom ports for develoment instance

---

docs/examples/how_do_i.md
docs/usage/misc/semantics.md
features/semantics.feature
lib/openhab/dsl/items/semantics.rb
lib/openhab/dsl/items/semantics/enumerable.rb

This will remove the need to call flat_map before calling Enumerable#points
Before:
```
Item.location
.equipments
.flat_map(&:members)
.points
```
after:
```
Item.location
.equipments
.points
```
Also add Enumerable#members, which is an idea from @ccutrer
This helps when doing something like `gLocation.equipments.members.member_of(NonSemanticGroup)`

feat(semantics): incorporate flat_map into Enumerable#points

---

features/step_definitions/openhab.rb
features/support/openhab_rest.rb

Another attempt to fix #576 
It seems that retrying the Rest / http request 5 times is futile, so I've removed that code here and instead restart openhab and retry.

test: restart openhab on persistent http error

---

docs/examples/how_do_i.md
docs/usage/misc/semantics.md
features/semantics.feature
lib/openhab/dsl/items/group_item.rb
lib/openhab/dsl/items/semantics.rb

* fix(semantics): groupitem.points failed to return its siblings because the code in Semantics#points never got called. This commit put the Semantics module ahead of Enumerable.
* fix(semantics): revert the members search for enumerable#points. There were some cases where descending into members is wrong.
* Move Semantics module into OpenHAB::DSL::Items to be consistent with Metadata and Persistence modules
* test(semantics): add tests to detect edge cases
* docs(semantics): improve semantics docs

fix(semantics): revert enumerable#points and fix a few edge cases

---

features/step_definitions/openhab.rb
features/support/openhab.rb

restart openhab when delete_rules failed. Encountered a condition where openhab had undeletable orphaned rules which lead to an exception raised by wait_until

test: restart openhab when delete_rules failed

---

docs/usage/misc/comparisons.md
features/items.feature
lib/openhab/dsl/items/generic_item.rb
lib/openhab/dsl/items/item_equality.rb
lib/openhab/dsl/types/point_type.rb
lib/openhab/dsl/types/type.rb

Fix #541 
* Add GenericItem#item method that returns GenericItemObject
* ItemEquality #== uses `eql?` when its argument is a GenericItemObject, i.e. `ItemName.item`
* This means users can use ItemName.item to ensure that they are operating on the item, not the state for equality comparison purposes
* Add ItemEquality #=== so that grep operates on the item without needing `.item`
* Update comparisons.md doc to clarify this issue

feat(item_equality): add the ability to compare item objects

---

docs/usage/misc/logging.md
features/logging.feature
lib/openhab/log/logger.rb

Resolve #569 
Change `logger#level_enabled?` to `logger#level?`
Alias deprecated level_enabled? for backwards compatibility

feat(logging): change logger level predicate method names

---

features/items.feature
lib/openhab/dsl/items/comparable_item.rb

Related to #550
It seems that we need to extend the item equality comparison into `<=>`
I came across an error when performing an item object comparison which involved <=> instead of ==.
I think it applies to anything involving comparable types, such as string, number, etc. Our current tests only involved Switch items hence why we didn't catch it.

fix: comparing non null vs null comparable-item objects raised an exception

---

docs/usage/misc/semantics.md
features/semantics.feature
lib/openhab/dsl/items/semantics.rb

For consistency's sake, rename `sublocations` to `locations`. The latter sounds more natural when being used on anything other than a location. e.g. `items.locations` vs `items.sublocations`
* Mark sublocations deprecated, but alias it to locations for compatibility
* Add more semantic examples

feat(semantics): rename sublocations to locations

---

.github/workflows/workflow.yml
features/ensure_states.feature
features/rule_language.feature
features/support/openhab.rb
rakelib/github.rake
rakelib/openhab.rake

Resolve #310
* I started off from @boc-tothefuture's work.
* a @log_level_changed was missing in one of the scenarios in rule_language.feature. The scenario set the log level to INFO causing subsequent tests using trace log to fail
* added `index` to the matrix array and use it in openhab dump file. Previously it used the very long feature names which also contain illegal characters `:` and `/`
Other non-essential changes:
* Added --no-heap-dump to dev:dump-create to reduce the openhab dump file size (in the case of test failures)
* Updated test against 3.3.0.M5
* Replaced / simplified several ruby setup actions with ruby/setup-ruby + bundler-cache in workflow.yml
* Close the file handle in truncate_log - I'm not sure whether the file handles would've gotten closed anyway by Ruby's GC at …

Optimize ci by reusing runners

---

lib/openhab/dsl/items/persistence.rb
rakelib/github.rake

#601 had a bug - it called the wrong method for between.
This PR should fix it, also upgraded the test to M7 where the between methods can actually be tested.

Persistence fix

---

features/step_definitions/openhab_rules.rb

This affects cucumber tests on my system, because my /tmp is on a separate mount. When using the Tempfile class and the tmp dir is in a different file system/mount, Openhab will load the file twice, resulting in incorrect operation.
Fix #595

ci(atomic_rule_write): create temp file in userdata/tmp

---

docs/usage/triggers/generic.md
features/generic_trigger.feature
features/persistence.feature
lib/openhab/core/thread_local.rb
lib/openhab/dsl/items/ensure.rb
lib/openhab/dsl/items/timed_command.rb
lib/openhab/dsl/timers/timer.rb
lib/openhab/log/logger.rb

This PR makes changes to the code base to be compatible with JRuby 9.4 / Ruby 3.x. It can be merged now because it is backwards compatible and should pass our current tests against jruby 9.3.
A separate draft PR will be created to add specific jruby 9.4 tests. That PR doesn't need to be merged yet until jruby 9.4 is in "beta".

Jruby94 compatibility

---

features/ensure_states.feature
features/rollershutter_item.feature
lib/openhab/dsl/items/dimmer_item.rb
lib/openhab/dsl/items/numeric_item.rb
lib/openhab/dsl/items/rollershutter_item.rb
lib/openhab/dsl/types/decimal_type.rb

previously it was getting converted to a straight string, which is
not comparable against a QuantityType. we might as well send
raw types through

fix(ensure): with QuantityType and plain number

---

.rubocop.yml
lib/openhab/core/entity_lookup.rb
lib/openhab/core/item_proxy.rb
lib/openhab/core/osgi.rb
lib/openhab/core/services.rb
lib/openhab/dsl/actions.rb
lib/openhab/dsl/group.rb
lib/openhab/dsl/items/item_registry.rb
lib/openhab/dsl/items/timed_command.rb
lib/openhab/dsl/monkey_patch/actions/script_thing_actions.rb
lib/openhab/dsl/rules/rule.rb
lib/openhab/dsl/things.rb

instead of having to disable it at each usage

chore(rubocop): explicitly allow openhab globals

---

lib/openhab/dsl/rules/rule.rb

fixes #620
we were changing the ID of the action after it was registered, so
when it unregistered it couldn't find its handler, and was orphaning
it. only to reuse the old handler on the reload because the id hadn't
been changed yet

fix(rules): fix reloading of rules

---

rakelib/openhab.rake

See https://community.openhab.org/t/jfrog-is-back-after-a-long-outage/138990

ci: update openhab source url to github
