- features/step_definitions/openhab_rules.rb
Cucumber test issued an error when checking whether the rule has been deployed when it shouldn't be.
When there is a runtime error in the rule, it's a rule problem, not a deployment problem. Before this fix, the test will fail saying that the deployment failed, not the test that failed. This is because it was checking for the log line that was inserted at the end of the rule. So when there's an error in the rule, that "Processing Complete for uid" never made it to the log.
This PR moves the logging to say "Processing Started for uid" before the test rule is executed, and the deploy_rule looks for this instead.
This solved two types of problems:
- As per PR #43 when the test rule has "sleep" in it, the Processing Complete didn't get written to the log file until after the script had …
> fix: cucumber deploy_rule checking

- lib/openhab/core/dsl/time_of_day.rb
> refactor: TimeOfDay.parse raises ArgumentError

- CHANGELOG.md
- Gemfile.lock
- docs/usage/items/switch.md
- features/switch_item.feature
- lib/openhab/core/dsl/monkey_patch/items/switch_item.rb
- lib/openhab/version.rb
> feat: Add SwitchItem.toggle

- docs/usage/misc/timers.md
Just a little addition to the Timer doc
> docs: list methods of the Timer object

- CHANGELOG.md
- Gemfile.lock
- docs/usage/misc/metadata.md
- features/metadata.feature
- features/step_definitions/openhab.rb
- features/support/openhab_rest.rb
- lib/openhab/core/dsl/monkey_patch/items/items.rb
- lib/openhab/core/dsl/monkey_patch/items/metadata.rb
- lib/openhab/osgi.rb
- lib/openhab/version.rb
I started afresh with this branch, based from the latest main branch. Credit to @boc-tothefuture for the original osgi and metadata delegator.
Resolve #15
> feat: add support for item metadata

- CHANGELOG.md
- Gemfile.lock
- features/string_item.feature
- lib/openhab/core/dsl/items/string_item.rb
- lib/openhab/version.rb
fix #40 
Add test scenario for stringitem to string and to stringitem comparison
bumped version number
updated changelog
> fix: StringItem comparison

- docs/usage/misc/metadata.md
Fix #95 
not sure if this will fix it?
> docs: fix metadata.md formatting

- docs/installation/index.md
See e.g. http://www.openhab.org/docs/installation/#getting-installation-info
> [Documentation] Change paths to conform with OpenHAB documentation

- features/number_item.feature
- features/quantity.feature
- lib/openhab/core/dsl/items/number_item.rb
- lib/openhab/core/dsl/monkey_patch/ruby/ruby.rb
- lib/openhab/core/dsl/types/quantity.rb
> fix(number_item): make math operations and comparisons work with Floats

- features/changed_duration.feature
- lib/openhab/core/dsl/rule/triggers/changed.rb
fix #105 
Should I update the changelog and version ?
> fix: multiple changed delays

- features/rule_language.feature
> test(rule_language): add test for library version in logs

- Gemfile.lock
- features/items.feature
- features/run.feature
- features/triggered.feature
- lib/openhab/core/dsl/entities.rb
- lib/openhab/core/dsl/group.rb
- lib/openhab/core/dsl/items/items.rb
- lib/openhab/core/dsl/rule/automation_rule.rb
> fix: decorate items[itemname], event.item, and triggered item

- Gemfile.lock
- lib/openhab/dsl/rules/automation_rule.rb
I hit this bug but I cannot reproduce it using a test scenario. Should we create a test scenario?
> fix(changed_duration): timer reschedule duration bug

- Gemfile.lock
- features/changed_duration.feature
- lib/openhab/dsl/rules/automation_rule.rb
> fix(changed_duration): guards not evaluated for changed duration

- features/persistence.feature
> test(persistence): improve timing on persistence test

- features/step_definitions/openhab.rb
- features/thing.feature
- lib/openhab/dsl/rules/automation_rule.rb
- lib/openhab/dsl/rules/triggers/changed.rb
~~Requires #164 to be merged first.~~
Fixes #162 
> fix(changed): for parameter with thing changed trigger

- docs/usage/misc/persistence.md
This seems to have been overwritten by another PR
Wait for #187
> docs(persistence): document the quantity conversion of persistence methods

- features/run.feature
- lib/openhab/dsl/monkey_patch/events/events.rb
- lib/openhab/dsl/monkey_patch/events/item_state.rb
This will add event.item to the run block for `updated` trigger
> feat(event): add event.state for update trigger

- docs/usage/items/dimmer.md
- features/dimmer_item.feature
- lib/openhab/dsl/items/datetime_item.rb
- lib/openhab/dsl/items/item_delegate.rb
- lib/openhab/dsl/items/number_item.rb
- lib/openhab/dsl/items/rollershutter_item.rb
- lib/openhab/dsl/items/string_item.rb
- lib/openhab/dsl/monkey_patch/items/dimmer_item.rb
> Item delegatation

- lib/openhab/dsl/monkey_patch/items/persistence.rb
I've just realised that some Persistence functions aren't supposed to be converted to Quantity. For example, `evolution_rate`. The returned value is the percentage of change.
This PR will apply the Quantity selectively.
> fix(persistence): selective conversion to Quantity

- features/groups.feature
- lib/openhab/dsl/group.rb
This addresses #180 
We have a broader #202 to address other group issues, I would like to have this one reviewed and released since a user was asking for it while we work through the broader strategic group issues.
> feat(groups): support command and <<

- features/changed.feature
- lib/openhab/dsl/rules/triggers/trigger.rb
> fix: triggering on multiple items caused a stack overflow

- features/rollershutter_item.feature
- lib/openhab/dsl/items/rollershutter_item.rb
> fix(rollershutter_item): add safe navigation and nil checks

- features/metadata_hash.feature
- lib/openhab/dsl/monkey_patch/items/metadata.rb
> fix(metadata): metadata config key hash mismatched

- features/every.feature
- features/gem_install.feature
- features/rule_language.feature
> fix: improve reliability of some tests

- features/quantity.feature
- lib/openhab/dsl/types/quantity.rb
> feat(quantity): implement positive?, negative?, and zero? for quantity and dimensioned numberitem

- features/step_definitions/openhab_rules.rb
- features/support/openhab.rb
* keep a persistent open connection to the openhab console, instead of
re-launching every time we need it
* don't do a REST query to ensure everything we just deleted is gone
when we didn't delete anything
> fix(tests): speed up tests by avoiding unnecessary work

- .releaserc.json
see https://github.com/Gusto/semantic-release-rubygem for docs on the option
> fix(build): have release process keep Gemfile.lock up to date

- .github/workflows/workflow.yml
- features/support/openhab.rb
- rakelib/github.rake
- rakelib/test.rake
Reverts boc-tothefuture/openhab-jruby#343
> build(ci): reverts splitting of features across runners

- .github/workflows/workflow.yml
- commitlint.config.js
> ci(commitlint): increase footer size

- lib/openhab/dsl/types/hsb_type.rb
> fix(hsb): fully qualify units class

- features/guards.feature
- lib/openhab/dsl/items/generic_item.rb
> fix(guard): only_if/not_if should work on all item types

- docs/usage/guards.md
- features/guards.feature
- lib/openhab/dsl/rules/guard.rb
> feat(guards): guards only_if/not_if support arrays of items

- lib/openhab/dsl/timers/timer.rb
> fix(timer): check the argument to reschedule

- docs/usage/guards/between.md
- features/between.feature
- lib/openhab.rb
- lib/openhab/dsl/between.rb
- lib/openhab/dsl/dsl.rb
- lib/openhab/dsl/items/dimmer_item.rb
- lib/openhab/dsl/rules/automation_rule.rb
- lib/openhab/dsl/rules/rule_config.rb
- lib/openhab/dsl/rules/triggers/cron.rb
- lib/openhab/dsl/time/month_day.rb
- lib/openhab/dsl/time/time_of_day.rb
- lib/openhab/dsl/types/date_time_type.rb
> feat(between): support for month-day ranges

- lib/openhab/dsl/items/metadata.rb
This should fix the failing metadata test on #379
> fix(metadata): return ruby hash inside metadata enumerator

- features/comparisons.feature
- lib/openhab/dsl/types/quantity_type.rb
> fix(quantity): fix comparison between integer on left and quantity on right

- docs/usage/items/color.md
- docs/usage/misc/types.md
- features/percent_type.feature
- lib/openhab/dsl/types/percent_type.rb
> feat(percenttype): add PercentType#scale and PercentType#to_byte

- features/actions.feature
- lib/openhab/dsl/actions.rb
This will enable having an item that contains the string to say or filename to play, and giving that item directly to say / play_sound / notify
> fix(actions): call to_s to accept item as an argument

- Gemfile.lock
Gemfile.lock keeps getting out of sync on my system. Would you mind merging this in please?
> fix(dev): add mac M1 platform to Gemfile.lock

- rakelib/github.rake
Waiting on https://github.com/openhab/openhab-distro/issues/1334
> ci: test against 3.2 Milestone 1

- features/received_command.feature
- lib/openhab/dsl/types/type.rb
Resolve #413
- Fix comparison errors between different types
- Improve tests for command predicates
> fix(comparisons): fix comparison errors between two types

- features/step_definitions/openhab.rb
- features/support/openhab.rb
> ci(regex): support regular expressions in log checks

- lib/openhab/dsl/rules/rule.rb
> fix(rule): rule method should return the rule object

- docs/usage/items.md
- features/items.feature
- lib/openhab/dsl/items/generic_item.rb
> feat(linked_thing): alias thing/things to linked_thing/all_linked_things

- docs/usage/items/switch.md
- features/switch_item.feature
- lib/openhab/dsl/items/switch_item.rb
> feat(switch): accept boolean values

- lib/openhab.rb
> fix(includes): remove redundant includes

- lib/openhab/dsl/rules/rule.rb
Resolve #438 
Not sure if this is the best solution but at least it works. 
Regression to #419
> fix(rule): rule return value caused namespace errors

- docs/usage/misc/type_comparisons.md
This adds the documentation for #417. It is far from perfect, so any feedback / improvements will be appreciated.
> docs(comparisons): document type comparisons

- docs/usage/triggers.md
- features/attachments.feature
- lib/openhab/dsl/rules/cron_trigger_rule.rb
- lib/openhab/dsl/rules/rule.rb
- lib/openhab/dsl/rules/rule_config.rb
- lib/openhab/dsl/rules/triggers/cron.rb
> feat(attach): support attachments on cron triggers

- docs/usage/misc/logging.md
- features/logging.feature
- features/step_definitions/openhab.rb
- lib/openhab.rb
- lib/openhab/core/openhab_setup.rb
- lib/openhab/core/thread_local.rb
- lib/openhab/dsl/items/image_item.rb
- lib/openhab/dsl/items/timed_command.rb
- lib/openhab/dsl/rules/automation_rule.rb
- lib/openhab/dsl/rules/rule.rb
- lib/openhab/dsl/rules/rule_config.rb
- lib/openhab/dsl/timers.rb
- lib/openhab/dsl/timers/reentrant_timer.rb
- lib/openhab/dsl/timers/timer.rb
- lib/openhab/log/logger.rb
> fix(logging): log rule name or file name with log entries

- docs/usage/items/datetime.md
- features/date_time_item.feature
- lib/openhab/dsl/items/date_time_item.rb
> feat(datetime): support ZonedDateTime objects as commands for DateTime items

- features/gem_install.feature
- features/step_definitions/openhab.rb
- features/support/env.rb
- features/support/openhab.rb
- rakelib/openhab.rake
Fixes PR #403 by changing the logging from binding to automation
> ci(bundle): use the official bundle

- features/item_timers.feature
- lib/openhab/dsl/items/timed_command.rb
> fix(timed_command): fix race condition for timed commands

- docs/usage/items/color.md
- features/color_item.feature
- lib/openhab/dsl/items/color_item.rb
> feat(hsb): add from/to hash support

- docs/usage/items/location.md
- features/location_item.feature
- lib/openhab/dsl/items/location_item.rb
- lib/openhab/dsl/types/point_type.rb
> feat(location): support hashes for locations

- features/timer.feature
- lib/openhab/dsl/timers/manager.rb
> fix(timer_manager): timers[nonexistent_id] should return nil

- docs/usage/misc/month_day.md
- features/month_day.feature
- lib/openhab/dsl/time/month_day.rb
> feat(month_day): support keyword arguments to create monthday

- features/guards.feature
- lib/openhab/dsl/rules/guard.rb
- lib/openhab/dsl/rules/rule.rb
> fix(guard): execute guard in main context

- docs/_config.yml
> docs(fix): specify remote theme

- features/between.feature
- features/month_day.feature
- lib/openhab/dsl/time/month_day.rb
Closes #479
Take a different approach (ignoring year) than #480
@jimtng are you ok with this approach?
> fix(monthday): fix monthday error when rolling over to another year

- features/comparisons.feature
- features/items.feature
- features/persistence.feature
- lib/openhab/core/entity_lookup.rb
- lib/openhab/core/item_proxy.rb
- lib/openhab/dsl/items/generic_item.rb
- lib/openhab/dsl/items/items.rb
- lib/openhab/dsl/states.rb
Implementation for discussion around #466
> feat(item): support reloading of references items

- features/ensure_states.feature
- lib/openhab/dsl/items/ensure.rb
> fix(ensure): faulty ensure on boolean commands

- features/rule_language.feature
- features/step_definitions/openhab.rb
- lib/openhab/dsl/rules/automation_rule.rb
- lib/openhab/dsl/rules/rule.rb
- lib/openhab/log/logger.rb
> fix(exception_handling): re-raising java exception caused an error

- features/support/openhab.rb
Performs retry as discussed in #493
> test(rest): retry rest requests on rules deletion

- docs/usage/triggers/changed.md
- docs/usage/triggers/updated.md
- features/changed.feature
- features/changed_duration.feature
- features/updated.feature
- lib/openhab/dsl/rules/automation_rule.rb
- lib/openhab/dsl/rules/rule_config.rb
- lib/openhab/dsl/rules/triggers/changed.rb
- lib/openhab/dsl/rules/triggers/conditions/duration.rb
- lib/openhab/dsl/rules/triggers/conditions/none.rb
- lib/openhab/dsl/rules/triggers/conditions/range.rb
- lib/openhab/dsl/rules/triggers/updated.rb
This PR supports ranges as rule conditions for from and to
Additionally, to support this some refactoring was done:
1. Change from @trigger_delays to @trigger_conditions 
2. Simplification of automation rule, but making TriggerDelay a TriggerCondition and moving it into its own class
> feat(rules): support ranges as rule conditions

- features/guards.feature
Addresses the issue with guards.feature test as discussed in #425
> test(guards): fix guards test

- features/persistence.feature
- lib/openhab/dsl/items/persistence.rb
> fix(persistence): NPE on dimensioned item without an explicit unit

- features/support/openhab.rb
Another attempt at fixing #493
> test(delete_rules): reset basic auth and retry on auth error

- features/quantity_type.feature
- lib/openhab/dsl/rules/triggers/conditions/proc.rb
> feat(triggers): support quantity string range in trigger conditions

- docs/usage/execution/run.md
Resolve #193
A minor change and one added line + markdown formatter adding/removing whitespaces.
> doc(run): add a note about was properties

- docs/usage/triggers/command.md
- features/received_command.feature
- lib/openhab/dsl/rules/triggers/command.rb
- lib/openhab/dsl/rules/triggers/conditions/proc.rb
> feat(command): received_command supports ranges and procs

- features/comparisons.feature
- lib/openhab/dsl/items/color_item.rb
- lib/openhab/dsl/types/hsb_type.rb
The solution was provided by @ccutrer
> fix(hsbtype): comparison against another hsbtype only checks for brightness

- features/timer.feature
- lib/openhab/dsl/timers.rb
- lib/openhab/dsl/timers/reentrant_timer.rb
- lib/openhab/dsl/timers/timer.rb
> Add create_timer and remove Timer class from top-level

- docs/contributing.md
- docs/examples/index.md
- docs/ruby-basics.md
- docs/usage/index.md
> docs: add ruby basics

- features/quantity_type.feature
- lib/openhab/dsl/items/numeric_item.rb
> fix(numeric_item): make NumericItem#| raise NoMethodError when state is nil

- docs/usage/misc/semantics.md
- features/semantics.feature
- features/step_definitions/openhab.rb
- features/support/openhab.rb
- features/support/openhab_rest.rb
- lib/openhab/dsl/items/ensure.rb
- lib/openhab/dsl/items/enumerable.rb
- lib/openhab/dsl/items/generic_item.rb
- lib/openhab/dsl/items/group_item.rb
- lib/openhab/dsl/items/items.rb
- lib/openhab/dsl/items/semantics.rb
- lib/openhab/dsl/items/semantics/enumerable.rb
refs #370
both direct wrapping of the action methods, as well as additional
convenience methods
> feat(semantics): add semantic helper methods to items

- features/support/openhab_rest.rb
Another attempt to resolve #576 
I'm still not sure what caused the "connection refused" error, but this wouldn't hurt.
* Change localhost to 127.0.0.1
* Implement retry on failure
At first I tried using the `retry` keyword inside the rescue block but it didn't seem to work. Doing the retry in a loop seems to do the trick.
> test(rest): retry on failure

- lib/openhab/dsl/rules/triggers/cron/cron.rb
- lib/openhab/dsl/states.rb
I messed up the yard documentation in my previous PRs. This PR fixes the inconsistencies.
> docs(yard): fix some yard errors

- docs/usage/misc/semantics.md
- lib/openhab/dsl/items/semantics.rb
https://github.com/openhab/openhab-core/pull/2928 which will change the meaning of Semantic getLocation and getEquipment.
Updating our docs correspondingly.
> docs: update yard descriptions for location and equipment

- docs/usage/triggers/generic.md
https://github.com/openhab/openhab-core/pull/2923
> docs: add an example for DateTimeTrigger

- docs/usage/misc/persistence.md
- features/persistence.feature
- lib/openhab/dsl/items/persistence.rb
Add support for https://github.com/openhab/openhab-core/pull/2931
> feat: add support for persistence 'between' methods

- lib/openhab/dsl/items/comparable_item.rb
missed passing through the argument when it got refactored out
> fix(items): ComparableItem#nil_comparison

- lib/openhab/dsl/monkey_patch/actions/script_thing_actions.rb
> fix(actions): don't use a singleton method for monkeypatching ScriptThingActions

- lib/openhab/dsl/rules/name_inference.rb
- lib/openhab/dsl/rules/rule.rb
- lib/openhab/dsl/rules/rule_config.rb
- lib/openhab/dsl/rules/terse.rb
- lib/openhab/dsl/rules/triggers/changed.rb
- lib/openhab/dsl/rules/triggers/channel.rb
- lib/openhab/dsl/rules/triggers/command.rb
- lib/openhab/dsl/rules/triggers/cron/cron.rb
- lib/openhab/dsl/rules/triggers/updated.rb
* push it down into rule itself, not just terse, but catch rules
that only have a single inferrable trigger
* support duration on item triggers
* support "every" triggers
* support channel triggers
* support multiple things for many parameters
> feat(rules): improve rule name inference

- lib/openhab/core/entity_lookup.rb
- lib/openhab/dsl/actions.rb
- lib/openhab/dsl/items/metadata.rb
- lib/openhab/dsl/items/persistence.rb
- lib/openhab/dsl/monkey_patch/events/thing_status_info.rb
- lib/openhab/dsl/monkey_patch/ruby/number.rb
- lib/openhab/dsl/rules/rule.rb
- lib/openhab/dsl/rules/triggers/conditions/duration.rb
- lib/openhab/dsl/rules/triggers/cron/cron.rb
- lib/openhab/dsl/timers/timer.rb
- lib/openhab/dsl/types/date_time_type.rb
- lib/openhab/dsl/types/hsb_type.rb
- lib/openhab/dsl/types/percent_type.rb
- lib/openhab/dsl/types/point_type.rb
- lib/openhab/dsl/types/quantity_type.rb
where possible (can't do it for inheritance)
> refactor: standardize on java format for java class references

- lib/openhab/dsl/types/decimal_type.rb
> fix(math): configure rounding params when doing BigDecimal division

- lib/openhab/log/logger.rb
> fix(logging): use the class name for class loggers
